pandas-helloworld-tryout:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v2
    # - name: run test
    #   env: # Or as an environment variable
    #     SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - run: |
        cd pandas-helloworld-tryout
          pipenv sync
          pipenv run python3 ./main.py
        cd ..
